package model;

// Target Types:

public enum SpellTarget {
    /*ANY_*/UNIT,
    ENEMY_UNIT,
    FRIENDLY_UNIT,
    ENEMY_HERO,
    FRIENDLY_HERO,
    ENEMY_MINION,
    FRIENDLY_MINION,
    GRID_2_2,
    GRID_3_3,
    GRID_2_2_UNITS,
    ALL_ENEMY_UNITS,
    ALL_FRIENDLY_UNITS,
    ALL_ENEMY_MINIONS_IN_ONE_COLUMN,
    RANDOM_ADJACENT_MINION,
    ADJACENT_MINIONS,
    MINIONS_WITHIN_DISTANCE_2,
    FRIENDLY_MINIONS_WITHIN_DISTANCE_2,
    ADJACENT_MINIONS_INCLUSIVE,
    RANDOM_ENEMY_UNIT,
    ENEMY_ADJACENT_MINIONS,
    UNITS_IN_HERO_ROW,
    SELF
}
